In [1]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
# 创建一个全为0的5x3矩阵
x = torch.empty(5,3)
x

tensor([[4.0888e-13, 7.2587e-43, 4.0884e-13],
        [7.2587e-43, 4.0886e-13, 7.2587e-43],
        [4.0886e-13, 7.2587e-43, 4.0884e-13],
        [7.2587e-43, 4.0884e-13, 7.2587e-43],
        [4.0885e-13, 7.2587e-43, 4.0885e-13]])

In [3]:
# 创建一个随机矩阵
x = torch.rand(5,3)
x

tensor([[0.0840, 0.8411, 0.3887],
        [0.9234, 0.0475, 0.3064],
        [0.3914, 0.2419, 0.1876],
        [0.3999, 0.0638, 0.5622],
        [0.0711, 0.7649, 0.4314]])

In [4]:
# 创建一个全为0，且数据类型为long的矩阵
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
# 将数据转化为张量
data = [
    [5,3],
    [2,6]
]
x = torch.tensor(data)
x

tensor([[5, 3],
        [2, 6]])

In [6]:
data = np.array([
    [5,3],
    [2,6]
])
x = torch.tensor(data)
x

tensor([[5, 3],
        [2, 6]], dtype=torch.int32)

In [7]:
# 根据已有的tensor建立新的tensor，除非用户提供新的值，否则这些方法将重用输入张量的属性
x = x.new_ones(5,3,dtype=torch.double) # new_* methods take in sizes
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [8]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[-0.2376,  1.9415, -0.6304],
        [ 0.3284,  0.8042,  0.6505],
        [ 1.1103,  2.0839, -0.0392],
        [-0.2689,  0.5200,  0.2402],
        [ 0.6214, -1.0464, -1.1207]])

In [9]:
# 获取张量的形状
x.size()
# torch.Size本质上还是tuple，所以支持tuple的一切操作。

torch.Size([5, 3])

In [10]:
# 运算
## 加法
y = torch.rand(5,3)
x+y

tensor([[ 0.1303,  2.3456, -0.3983],
        [ 0.7492,  1.0057,  1.1466],
        [ 1.3988,  2.1539, -0.0265],
        [ 0.1278,  1.2550,  1.0558],
        [ 1.0916, -0.7066, -0.3293]])

In [11]:
torch.add(x,y)

tensor([[ 0.1303,  2.3456, -0.3983],
        [ 0.7492,  1.0057,  1.1466],
        [ 1.3988,  2.1539, -0.0265],
        [ 0.1278,  1.2550,  1.0558],
        [ 1.0916, -0.7066, -0.3293]])

In [12]:
# 给定一个输出张量作为参数
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[ 0.1303,  2.3456, -0.3983],
        [ 0.7492,  1.0057,  1.1466],
        [ 1.3988,  2.1539, -0.0265],
        [ 0.1278,  1.2550,  1.0558],
        [ 1.0916, -0.7066, -0.3293]])

In [13]:
# 原地进行运算
y.add_(x)
y
# 任何一个in-place改变张量的操作后面都固定一个_。例如x.copy_(y)、x.t_()将更改x

tensor([[ 0.1303,  2.3456, -0.3983],
        [ 0.7492,  1.0057,  1.1466],
        [ 1.3988,  2.1539, -0.0265],
        [ 0.1278,  1.2550,  1.0558],
        [ 1.0916, -0.7066, -0.3293]])

In [14]:
# 也可以使用像标准的NumPy一样的各种索引操作：
x[:,1]

tensor([ 1.9415,  0.8042,  2.0839,  0.5200, -1.0464])

In [15]:
# 改变形状：如果想改变形状，可以使用torch.view
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
x.size(),y.size(),z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [16]:
# 如果是仅包含一个元素的tensor，可以使用.item()来得到对应的python数值
x = torch.randn(1)
x,x.item()

(tensor([-2.0118]), -2.0118377208709717)

In [17]:
# 超过100种tensor的运算操作，包括转置，索引，切片，数学运算， 线性代数，随机数等，具体访问这里
# https://pytorch.org/docs/stable/torch.html

In [18]:
# 将一个Torch张量转换为一个NumPy数组是轻而易举的事情，反之亦然。
# Torch张量和NumPy数组将共享它们的底层内存位置，因此当一个改变时,另外也会改变。


In [19]:
# 将torch的Tensor转化为NumPy数组
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [20]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [21]:
# 看NumPy数组是如何改变里面的值的：
a.add_(1)
a,b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [22]:
# 将NumPy数组转化为Torch张量
## 看改变NumPy数组是如何自动改变Torch张量的：
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
a,b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [23]:
# CPU上的所有张量(CharTensor除外)都支持与Numpy的相互转换。

In [24]:
# CUDA上的张量
## 张量可以使用.to方法移动到任何设备(device）上：

In [25]:
# 当GPU可用时,可以运行以下代码
# 将使用`torch.device`来将tensor移入和移出GPU

if torch.cuda.is_available():
    device = torch.device("cuda") # CUDA设备对象
    y = torch.ones_like(x,device=device) # 直接在GPU上创建tensor
    x = x.to(device) # 或者使用'.to("cuda")'方法
    z = x+y
    print(z)
    print(z.to("cpu",torch.double)) # '.to'也能在移动时改变dtype

tensor([-1.0118], device='cuda:0')
tensor([-1.0118], dtype=torch.float64)
