In [1]:
import torch
import numpy as np

In [2]:
# 创建一个张量并设置requires_grad=True用来追踪其计算历史
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
# 对这个张量做一次运算：
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
# 对y进行更多操作
z = y*y*3
out = z.mean()
z,out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [5]:
# .requires_grad_(...) 原地改变了现有张量的 requires_grad 标志。
# 如果没有指定的话，默认输入的这个标志是 False。
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [6]:
# 梯度
## 现在开始进行反向传播，因为 out 是一个标量，
## 因此 out.backward() 和 out.backward(torch.tensor(1.)) 等价。
out.backward()
# 输出导数 d(out)/dx

In [7]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [76]:
x = torch.ones(2,2,requires_grad=True)
y = 3*(x+2)**2
y.backward(torch.ones(x.size())) # dy/dx = 3*2*(x+2) = 6*(x+2)
x.grad

tensor([[18., 18.],
        [18., 18.]])

In [71]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([863.8564, 526.8645, -22.4980], grad_fn=<MulBackward0>)


In [73]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [79]:
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
False
